defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address=":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$qV96xSuQ$y3da6TZxscGOI3dCCQpfO/"]  
  [entryPoints.http]
    address=":80"
    [entryPoints.http.redirect]
        entryPoint="https"
  [entryPoints.https]
    address=":443"
    [entryPoints.http.tls]



[api]
entrypoint="dashboard"

[acme]
email="siddverma1999@gmail.com"
storage="acme.json"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint="https"
onHostRule=true
  [acme.httpChallenge]
  entryPoint="http"

[docker]
domain="gin-learn.siddharthavarma.tech"
watch=true
network="web"
