defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.dashboard]
    address=":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$dIQBeY8w$nTxNUvcLNR/v4FEcv59WQ."]

[api]
entrypoint="dashboard"

[entryPoints.http]
  address=":80"
    [entryPoints.http.redirect]
      entryPoint="https"
[entryPoints.https]
  address=":443"
    [entryPoints.http.tls]


[acme]
email="siddverma1999@gmail.com"
storage="acme.json"
entryPoint="https"
onHostRule=true
  [acme.httpChallenge]
  entryPoint="http"

[docker]
domain="gin-learn.siddharthavarma.tech"
watch=true
network="web"
