logLevel = "WARN"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address=":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$ELRnnboi$/Kn2hQFXgL9IK.GhVo3DW0"]  
  [entryPoints.http]
    address=":80"
    [entryPoints.http.redirect]
        entryPoint="https"
  [entryPoints.https]
    address=":443"
    [entryPoints.http.tls]



[api]
entrypoint="dashboard"
# entrypoint="traefik"
# dashboard=true
# address=":8080"

[acme]
email="siddverma1999@gmail.com"
storage="acme.json"
entryPoint="https"
onHostRule=true
  [acme.httpChallenge]
  entryPoint="http"
onDemand=false
  [acme.dnsChallenge]
    provider="digitalocean"
    delayBeforeCheck=0

[docker]
domain="gin-learn.siddharthavarma.tech"
watch=true
network="web"

